name: Release

on: 
  push:
    tags:
    - '*'
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Determine Tag
      id: get_tag
      run: echo "::set-output name=tag::${{ github.ref_name || github.event.inputs.release_version }}"

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "hashdb.py"
        omitBody: true
        tag: ${{ steps.get_tag.outputs.tag }}
        token: ${{ secrets.GITHUB_TOKEN }}
